# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  inject:
    import: "package:inject_generator/inject_generator.dart"
    builder_factories: [ "injectBuilder" ]
    build_extensions: { r'$lib$': [ "setup_dependencies.dart" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen" ]