name: inject_generator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^8.0.0
  async: ^2.8.0
  build: ^3.0.0
  build_config: ^1.0.0
  build_runner: ^2.3.3
  collection: ^1.14.0
  dart_style: any
  glob: any
  inject:
    git: 'https://github.com/lamtx/inject.git'
  meta: ^1.7.0
  path: ^1.8.0
  path_to_regexp: ^0.4.0
  source_gen: ^3.0.0
  source_helper: ^1.0.0
dev_dependencies:
  source_gen_test: ^1.0.0
  test: ^1.21.0